<?php echo $this->partial('wizard/header', ['wizard' => $this->wizard]) ?>
<?php
$wizardForm = $this->wizard->getForm();
$wizardForm->prepare();

$currentStep = $this->wizard->getCurrentStep();
?>
<form>
    <?php
    echo $this->partial($currentStep->getOptions()->getViewTemplate(), [
        'form' => $wizardForm->get('step')
    ]);
    ?>
    <?php echo $this->partial('wizard/buttons', ['wizard' => $this->wizard]) ?>
</form>