<?php echo $this->partial('wizard/header', array('wizard' => $this->wizard)) ?>
<?php
$wizardForm = $this->wizard->getForm();
$wizardForm->prepare();

$currentStep = $this->wizard->getCurrentStep();
?>
<form>
    <?php
    echo $this->partial($currentStep->getViewTemplate(), array(
        'form' => $wizardForm->get('step')
    ));
    ?>
    <?php echo $this->partial('wizard/buttons', array('wizard' => $this->wizard)) ?>
</form>